# ============================================================
# BUILDA-APK.ps1
# Script per costruire l'APK direttamente da OneDrive
# Uso: tasto destro -> "Esegui con PowerShell"
#      oppure da terminale: .\BUILDA-APK.ps1
# ============================================================

$root = "C:\Users\ercole\OneDrive\rpg-initiative-tracker"
$pluginsDir = "$root\android\capacitor-cordova-android-plugins"
$assetsPublic = "$root\android\app\src\main\assets\public"

# Contenuto dei file gradle (usato dopo cap sync)
$cordovaVars = @'
// DO NOT EDIT THIS FILE! IT IS GENERATED EACH TIME "capacitor update" IS RUN
ext {
  cdvMinSdkVersion = project.hasProperty('minSdkVersion') ? rootProject.ext.minSdkVersion : 22
  // Plugin gradle extensions can append to this to have code run at the end.
  cdvPluginPostBuildExtras = []
  cordovaConfig = [:]
}
'@

$buildGradle = @'
ext {
    androidxAppCompatVersion = project.hasProperty('androidxAppCompatVersion') ? rootProject.ext.androidxAppCompatVersion : '1.6.1'
    cordovaAndroidVersion = project.hasProperty('cordovaAndroidVersion') ? rootProject.ext.cordovaAndroidVersion : '10.1.1'
}

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.1'
    }
}

apply plugin: 'com.android.library'

android {
    namespace "capacitor.cordova.android.plugins"
    compileSdk project.hasProperty('compileSdkVersion') ? rootProject.ext.compileSdkVersion : 34
    defaultConfig {
        minSdkVersion project.hasProperty('minSdkVersion') ? rootProject.ext.minSdkVersion : 22
        targetSdkVersion project.hasProperty('targetSdkVersion') ? rootProject.ext.targetSdkVersion : 34
        versionCode 1
        versionName "1.0"
    }
    lintOptions {
        abortOnError false
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

repositories {
    google()
    mavenCentral()
    flatDir{
        dirs 'src/main/libs', 'libs'
    }
}

dependencies {
    implementation fileTree(dir: 'src/main/libs', include: ['*.jar'])
    implementation "androidx.appcompat:appcompat:$androidxAppCompatVersion"
    implementation "org.apache.cordova:framework:$cordovaAndroidVersion"
    // SUB-PROJECT DEPENDENCIES START

    // SUB-PROJECT DEPENDENCIES END
}

// PLUGIN GRADLE EXTENSIONS START
apply from: "cordova.variables.gradle"
// PLUGIN GRADLE EXTENSIONS END

for (def func : cdvPluginPostBuildExtras) {
    func()
}
'@

Write-Host ""
Write-Host "=== STEP 2: Rimuovo cartelle bloccate da OneDrive ===" -ForegroundColor Cyan

# Rimuovi assets/public
if (Test-Path $assetsPublic) {
    Remove-Item -Recurse -Force $assetsPublic -ErrorAction SilentlyContinue
    Write-Host "  OK: assets/public rimosso" -ForegroundColor Green
} else {
    Write-Host "  OK: assets/public non esiste, nulla da fare" -ForegroundColor Green
}

# Rimuovi TUTTA la cartella capacitor-cordova-android-plugins (OneDrive blocca src e build)
# cap sync la ricreerà da zero
if (Test-Path $pluginsDir) {
    Remove-Item -Recurse -Force $pluginsDir -ErrorAction SilentlyContinue
    Write-Host "  OK: capacitor-cordova-android-plugins rimossa completamente" -ForegroundColor Green
} else {
    Write-Host "  OK: capacitor-cordova-android-plugins non esiste, nulla da fare" -ForegroundColor Green
}

Write-Host ""
Write-Host "=== STEP 3: npx cap sync android ===" -ForegroundColor Cyan
Set-Location $root
& npx cap sync android 2>&1 | Tee-Object -Variable capOutput | ForEach-Object { Write-Host $_ }
# cap sync può fallire su "update android" ma aver già copiato i web assets (quello che ci serve)
# Verifichiamo se almeno la copia dei web assets è riuscita
$copyOk = $capOutput | Where-Object { $_ -match "copy android" -and $_ -match "√|Copying web assets" }
if ($LASTEXITCODE -ne 0) {
    Write-Host "  ATTENZIONE: cap sync ha riportato un errore, ma procedo lo stesso..." -ForegroundColor Yellow
}
Write-Host "  OK: cap sync completato" -ForegroundColor Green

Write-Host ""
Write-Host "=== STEP 4: Creo i file Gradle necessari ===" -ForegroundColor Cyan
New-Item -ItemType Directory -Force -Path $pluginsDir | Out-Null
# Usa UTF-8 senza BOM (Gradle non accetta il BOM di PowerShell)
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText("$pluginsDir\cordova.variables.gradle", $cordovaVars, $utf8NoBom)
[System.IO.File]::WriteAllText("$pluginsDir\build.gradle", $buildGradle, $utf8NoBom)
Write-Host "  OK: file Gradle creati (UTF-8 senza BOM)" -ForegroundColor Green

# Assicura che src/main/res esista e .gitkeep sia un file vero (non un placeholder OneDrive)
$resDir = "$pluginsDir\src\main\res"
$gitkeep = "$resDir\.gitkeep"
New-Item -ItemType Directory -Force -Path $resDir | Out-Null
# Se .gitkeep esiste come directory (placeholder OneDrive), rimuovila e ricreala come file
if (Test-Path $gitkeep -PathType Container) {
    Remove-Item -Recurse -Force $gitkeep -ErrorAction SilentlyContinue
}
[System.IO.File]::WriteAllText($gitkeep, "", $utf8NoBom)
Write-Host "  OK: src/main/res/.gitkeep creato come file" -ForegroundColor Green

Write-Host ""
Write-Host "=== STEP 5: Build APK debug ===" -ForegroundColor Cyan
Set-Location "$root\android"
$gradleOut = & .\gradlew.bat assembleDebug 2>&1
Write-Host $gradleOut

$apkBuildPath = "C:\Users\ercole\AppData\Local\rpg-android-build\app\outputs\apk\debug\app-debug.apk"
$apkDestPath = "$root\app-debug.apk"
if ($LASTEXITCODE -eq 0 -and (Test-Path $apkBuildPath)) {
    # Copia APK nella cartella del progetto su OneDrive per comodità
    Copy-Item $apkBuildPath $apkDestPath -Force
    Write-Host ""
    Write-Host "========================================" -ForegroundColor Green
    Write-Host "  APK CREATO CON SUCCESSO!" -ForegroundColor Green
    Write-Host "  Build: $apkBuildPath" -ForegroundColor Green
    Write-Host "  Copia: $apkDestPath" -ForegroundColor Green
    Write-Host "========================================" -ForegroundColor Green
} else {
    Write-Host ""
    Write-Host "  ERRORE durante la build Gradle!" -ForegroundColor Red
    Write-Host "  Controlla l'output sopra per i dettagli." -ForegroundColor Red
}

Write-Host ""
Read-Host "Premi INVIO per uscire"
