# ============================================================
# BUILDA-APK.ps1
# Costruisce l'APK Android del progetto RPG Initiative Tracker.
#
# - Lavora dalla cartella in cui si trova lo script (portable: niente path
#   hardcoded a OneDrive). Il progetto vive in C:\dev\InitiativeTracker.
# - Output Gradle: $root\dist\android-build\... (vedi android\build.gradle).
# - APK finale: $root\dist\RPG-Initiative-Tracker-debug.apk.
#
# Uso: tasto destro -> "Esegui con PowerShell"
#      oppure da terminale: .\BUILDA-APK.ps1
# ============================================================

$ErrorActionPreference = "Stop"

# Root portable: la cartella in cui sta questo script
$root         = $PSScriptRoot
$pluginsDir   = Join-Path $root "android\capacitor-cordova-android-plugins"
$assetsPublic = Join-Path $root "android\app\src\main\assets\public"
$distDir      = Join-Path $root "dist"
$apkBuildPath = Join-Path $root "dist\android-build\app\outputs\apk\debug\app-debug.apk"
$apkDestPath  = Join-Path $distDir "RPG-Initiative-Tracker-debug.apk"

Write-Host ""
Write-Host "=== RPG Initiative Tracker - Build APK ===" -ForegroundColor Cyan
Write-Host "Root progetto: $root" -ForegroundColor Gray
Write-Host "APK finale:    $apkDestPath" -ForegroundColor Gray
Write-Host ""

# Contenuto dei file Gradle ricreati DOPO cap sync (vengono cancellati e
# ricreati a ogni run perche' OneDrive li bloccava in passato; sul nuovo
# path C:\dev non serve piu', ma manteniamo il flusso per robustezza).
$cordovaVars = @'
// DO NOT EDIT THIS FILE! IT IS GENERATED EACH TIME "capacitor update" IS RUN
ext {
  cdvMinSdkVersion = project.hasProperty('minSdkVersion') ? rootProject.ext.minSdkVersion : 23
  // Plugin gradle extensions can append to this to have code run at the end.
  cdvPluginPostBuildExtras = []
  cordovaConfig = [:]
}
'@

$buildGradle = @'
ext {
    androidxAppCompatVersion = project.hasProperty('androidxAppCompatVersion') ? rootProject.ext.androidxAppCompatVersion : '1.6.1'
    cordovaAndroidVersion = project.hasProperty('cordovaAndroidVersion') ? rootProject.ext.cordovaAndroidVersion : '10.1.1'
}

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.1'
    }
}

apply plugin: 'com.android.library'

android {
    namespace "capacitor.cordova.android.plugins"
    compileSdk project.hasProperty('compileSdkVersion') ? rootProject.ext.compileSdkVersion : 35
    defaultConfig {
        minSdkVersion project.hasProperty('minSdkVersion') ? rootProject.ext.minSdkVersion : 23
        targetSdkVersion project.hasProperty('targetSdkVersion') ? rootProject.ext.targetSdkVersion : 35
        versionCode 1
        versionName "1.0"
    }
    lintOptions {
        abortOnError false
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

repositories {
    google()
    mavenCentral()
    flatDir{
        dirs 'src/main/libs', 'libs'
    }
}

dependencies {
    implementation fileTree(dir: 'src/main/libs', include: ['*.jar'])
    implementation "androidx.appcompat:appcompat:$androidxAppCompatVersion"
    implementation "org.apache.cordova:framework:$cordovaAndroidVersion"
    // SUB-PROJECT DEPENDENCIES START

    // SUB-PROJECT DEPENDENCIES END
}

// PLUGIN GRADLE EXTENSIONS START
apply from: "cordova.variables.gradle"
// PLUGIN GRADLE EXTENSIONS END

for (def func : cdvPluginPostBuildExtras) {
    func()
}
'@

# UTF-8 SENZA BOM (Gradle non accetta il BOM di PowerShell)
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)

# ------------------------------------------------------------
# STEP 1: kill di processi gradle/java zombie che lockano i file.
# (Lesson learned: dopo un Ctrl-C resta un Java daemon che blocca .jar)
# ------------------------------------------------------------
Write-Host "=== STEP 1: Kill processi Gradle/Java zombie ===" -ForegroundColor Cyan
Get-Process -ErrorAction SilentlyContinue java, gradle, kotlin-compiler-daemon |
    Where-Object { $_.Path -and $_.Path -like "*$root*" -or $_.Path -like "*gradle*" -or $_.Path -like "*android*" } |
    ForEach-Object {
        Write-Host "  Killing PID $($_.Id) ($($_.ProcessName))" -ForegroundColor Yellow
        Stop-Process -Id $_.Id -Force -ErrorAction SilentlyContinue
    }
Start-Sleep -Milliseconds 500
Write-Host "  OK" -ForegroundColor Green

# ------------------------------------------------------------
# STEP 2: pulizia cartelle che danno problemi tra una build e l'altra.
# ------------------------------------------------------------
Write-Host ""
Write-Host "=== STEP 2: Pulizia assets/public e capacitor-cordova-android-plugins ===" -ForegroundColor Cyan

if (Test-Path $assetsPublic) {
    Remove-Item -Recurse -Force $assetsPublic -ErrorAction SilentlyContinue
    Write-Host "  OK: assets/public rimosso" -ForegroundColor Green
} else {
    Write-Host "  OK: assets/public non esiste, nulla da fare" -ForegroundColor Green
}

# capacitor-cordova-android-plugins viene rigenerata da cap sync
if (Test-Path $pluginsDir) {
    Remove-Item -Recurse -Force $pluginsDir -ErrorAction SilentlyContinue
    Write-Host "  OK: capacitor-cordova-android-plugins rimossa" -ForegroundColor Green
} else {
    Write-Host "  OK: capacitor-cordova-android-plugins non esiste, nulla da fare" -ForegroundColor Green
}

# ------------------------------------------------------------
# STEP 3: cap sync android (copia public/ -> android/app/src/main/assets/public)
# ------------------------------------------------------------
Write-Host ""
Write-Host "=== STEP 3: npx cap sync android ===" -ForegroundColor Cyan
Set-Location $root
& npx cap sync android 2>&1 | Tee-Object -Variable capOutput | ForEach-Object { Write-Host $_ }
if ($LASTEXITCODE -ne 0) {
    Write-Host "  ATTENZIONE: cap sync ha riportato un errore, ma procedo lo stesso" -ForegroundColor Yellow
    Write-Host "  (spesso 'update android' fallisce ma 'copy android' e' gia' andato OK)" -ForegroundColor Yellow
}
Write-Host "  OK: cap sync completato" -ForegroundColor Green

# ------------------------------------------------------------
# STEP 4: ricreo i file Gradle dei plugin cordova (cap sync li svuota).
# ------------------------------------------------------------
Write-Host ""
Write-Host "=== STEP 4: Creo i file Gradle dei plugin cordova ===" -ForegroundColor Cyan
New-Item -ItemType Directory -Force -Path $pluginsDir | Out-Null
[System.IO.File]::WriteAllText((Join-Path $pluginsDir "cordova.variables.gradle"), $cordovaVars, $utf8NoBom)
[System.IO.File]::WriteAllText((Join-Path $pluginsDir "build.gradle"),             $buildGradle, $utf8NoBom)
Write-Host "  OK: cordova.variables.gradle + build.gradle (UTF-8 senza BOM)" -ForegroundColor Green

# src/main/res/.gitkeep deve essere un FILE, non una directory.
# (Su OneDrive a volte e' una directory placeholder; manteniamo il fix per sicurezza.)
$resDir  = Join-Path $pluginsDir "src\main\res"
$gitkeep = Join-Path $resDir     ".gitkeep"
New-Item -ItemType Directory -Force -Path $resDir | Out-Null
if (Test-Path $gitkeep -PathType Container) {
    Remove-Item -Recurse -Force $gitkeep -ErrorAction SilentlyContinue
}
[System.IO.File]::WriteAllText($gitkeep, "", $utf8NoBom)
Write-Host "  OK: src/main/res/.gitkeep" -ForegroundColor Green

# ------------------------------------------------------------
# STEP 5: build APK debug con Gradle
#
# NOTA: javac stampa "Note: Some input files use unchecked or unsafe
# operations." sullo STDERR anche quando la build va a buon fine.
# Combinato con $ErrorActionPreference='Stop' e '2>&1 | ForEach-Object',
# PowerShell promuove quella riga di stderr a TERMINATING ERROR e killa
# lo script a meta' build (NativeCommandError). Soluzione: durante la
# chiamata a gradlew passiamo a 'Continue' e lasciamo che gradlew stampi
# direttamente a video, senza pipe. L'exit code lo leggiamo da $LASTEXITCODE.
# ------------------------------------------------------------
Write-Host ""
Write-Host "=== STEP 5: gradlew assembleDebug ===" -ForegroundColor Cyan
Set-Location (Join-Path $root "android")
$prevErrPref = $ErrorActionPreference
$ErrorActionPreference = 'Continue'
& .\gradlew.bat assembleDebug
$gradleExit = $LASTEXITCODE
$ErrorActionPreference = $prevErrPref
Set-Location $root

# ------------------------------------------------------------
# STEP 6: copia APK in dist\
# ------------------------------------------------------------
Write-Host ""
Write-Host "=== STEP 6: Copia APK in dist\ ===" -ForegroundColor Cyan
New-Item -ItemType Directory -Force -Path $distDir | Out-Null

if ($gradleExit -eq 0 -and (Test-Path $apkBuildPath)) {
    Copy-Item $apkBuildPath $apkDestPath -Force
    $sizeKb = [math]::Round((Get-Item $apkDestPath).Length / 1KB, 0)
    Write-Host ""
    Write-Host "========================================" -ForegroundColor Green
    Write-Host "  APK CREATO CON SUCCESSO!" -ForegroundColor Green
    Write-Host "  Build interna : $apkBuildPath" -ForegroundColor Green
    Write-Host "  APK finale    : $apkDestPath" -ForegroundColor Green
    Write-Host "  Dimensione    : $sizeKb KB" -ForegroundColor Green
    Write-Host "========================================" -ForegroundColor Green
    Write-Host ""
    Write-Host "  Trasferisci l'APK al telefono via USB / Telegram / Drive" -ForegroundColor Cyan
    Write-Host "  e installalo (Impostazioni -> consenti origini sconosciute)." -ForegroundColor Cyan
} else {
    Write-Host ""
    Write-Host "  ERRORE durante la build Gradle (exit $gradleExit)" -ForegroundColor Red
    if (-not (Test-Path $apkBuildPath)) {
        Write-Host "  APK non trovato a: $apkBuildPath" -ForegroundColor Red
    }
    Write-Host "  Controlla l'output sopra per i dettagli." -ForegroundColor Red
    exit 1
}

Write-Host ""
Read-Host "Premi INVIO per uscire"
